### ISSUE TITLE
imutypes.cc 

### ISSUE THREAD

**Issue by AcresJoe1** [mingjitianming/ORB_SLAM3_annotation#1]
您好！ 请问一下imutypes.h 这个脚本里面定义的cv::Mat C和imutypes.cc使用到的C指的是协方差矩阵吗？

**Comment by mingjitianming** [comment]
是的，这里imu预积分的状态使用的是R,V,P,ba,bg,C是对应的15x15的协方差矩阵

**Comment by mingjitianming** [comment]
> 您好！ 请问一下imutypes.h 这个脚本里面定义的cv::Mat C和imutypes.cc使用到的C指的是协方差矩阵吗？

是的，这里imu预积分的状态使用的是R,V,P,ba,bg,C是对应的15x15的协方差矩阵

**Comment by AcresJoe1** [comment]
好的，非常感谢您！ 我还想请教一下这个协方差矩阵C能不能用来表征IMU定位的不确定度呀？或者用类似的方法去求位姿的不确定度？

**Comment by mingjitianming** [comment]
> 好的，非常感谢您！ 我还想请教一下这个协方差矩阵C能不能用来表征IMU定位的不确定度呀？或者用类似的方法去求位姿的不确定度？

协方差C是可以表征当前imu定位的不确定性的，这里的imu预积分更新包含了标量(nominal)和小量(error)的更新,小量更新主要是用来更新协方差来表征不确定性的变化

**Comment by AcresJoe1** [comment]
因为我之前了解到协方差矩阵是对称的，但是我打印出来C是一个不对称的矩阵，所以不太理解它的更新方式，您上面提到的标量和小量具体指的是？另外下面的Nga和NgaWalk代表的是什么意思呀？
 C.rowRange(0,9).colRange(0,9) = A*C.rowRange(0,9).colRange(0,9)*A.t() + B*Nga*B.t();
 C.rowRange(9,15).colRange(9,15) = C.rowRange(9,15).colRange(9,15) + NgaWalk;

**Comment by mingjitianming** [comment]
1. Nga表示的是imu线加速度和角速度的噪声，NgaWalk表示imu ba，bg的噪声
2. C不是完全对称(数值偏差较小)是正常的(个人感觉)，当然如果数值偏差过大就应该检查下是否有错误了
3. 这里imu预积分推到类似于eskf将变量分解为标量和误差，如 

$$\hat{v} = \bar{v} + \delta{v}$$

协方差更新方程是根据误差推到得到的
建议你先看一下这篇论文:On-Manifold Preintegration for Real-Time Visual-Inertial Odometry

**Comment by mingjitianming** [comment]
> 因为我之前了解到协方差矩阵是对称的，但是我打印出来C是一个不对称的矩阵，所以不太理解它的更新方式，您上面提到的标量和小量具体指的是？另外下面的Nga和NgaWalk代表的是什么意思呀？
> C.rowRange(0,9).colRange(0,9) = A_C.rowRange(0,9).colRange(0,9)_A.t() + B_Nga_B.t();
> C.rowRange(9,15).colRange(9,15) = C.rowRange(9,15).colRange(9,15) + NgaWalk;

1. Nga表示的是imu线加速度和角速度的噪声，NgaWalk表示imu ba，bg的噪声
2. C不是完全对称(数值偏差较小)是正常的(个人感觉)，当然如果数值偏差过大就应该检查下是否有错误了
3. 这里imu预积分推到类似于eskf将变量分解为标量和误差，如 

$$\hat{v} = \bar{v} + \delta{v}$$

协方差更新方程是根据误差推到得到的
建议你先看一下这篇论文:On-Manifold Preintegration for Real-Time Visual-Inertial Odometry

**Comment by AcresJoe1** [comment]
好的，谢谢你哦！
